import type { Metadata } from "next";
import { Geist_Mono, Inter, Sora, DM_Sans } from "next/font/google"; // ✅ add DM_Sans
import "./globals.css";
import NetworkGuard from "@/components/network/NetworkGuard"

const headingFont = Sora({
  variable: "--font-heading",
  subsets: ["latin"],
});

const bodyFont = Inter({
  variable: "--font-body",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ add this
const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){var t=localStorage.getItem('theme');if(t==='dark'||(!t&&window.matchMedia('(prefers-color-scheme: dark)').matches))document.documentElement.classList.add('dark');else document.documentElement.classList.remove('dark');})();`,
          }}
        />
      </head>
      <body
        className={`${headingFont.variable} ${bodyFont.variable} ${geistMono.variable} ${dmSans.variable} antialiased flex min-h-screen flex-col`} // ✅ add dmSans.variable
      >
        <NetworkGuard>{children}</NetworkGuard>
      </body>
    </html>
  );
}